"use client";
import { useState } from "react";
import { saveBillingSettings } from "@/server/billing/actions";
import type { getBillingSettings } from "@/server/billing/queries";
import { BillingNav } from "@/components/billing/nav";

type Values = NonNullable<Awaited<ReturnType<typeof getBillingSettings>>>;
export function BillingSettings({ values }: { values: Values | null }) {
  const [message, setMessage] = useState<string>();
  if (!values) return <div className="page billing-page"><BillingNav /><div className="info-bar">Choose one outlet in the header to configure billing.</div></div>;
  async function submit(data: FormData) { const result = await saveBillingSettings({ blockOnLimitBreach: data.get("blockOnLimitBreach") === "on", blockOnOverdue: data.get("blockOnOverdue") === "on", autoRoundOff: data.get("autoRoundOff") === "on", defaultPrintLayout: data.get("defaultPrintLayout"), smsProvider: data.get("smsProvider"), smsEndpoint: data.get("smsEndpoint"), smsApiKey: data.get("smsApiKey"), smsSender: data.get("smsSender"), emailProvider: data.get("emailProvider"), emailEndpoint: data.get("emailEndpoint"), emailApiKey: data.get("emailApiKey"), emailFrom: data.get("emailFrom") }); setMessage(result.ok ? "Billing and delivery settings saved." : result.error); }
  return <div className="page billing-page"><BillingNav /><div className="section-head"><div><p className="eyebrow">OUTLET POLICY</p><h1>Billing settings</h1><p className="muted page-lede">Credit enforcement, invoice defaults and pluggable customer delivery providers.</p></div></div>{message && <div className="info-bar">{message}</div>}<form action={submit} className="settings-grid"><section className="panel settings-card"><p className="eyebrow">CREDIT CONTROL</p><h2>Approval policy</h2><label className="check-row"><input name="blockOnLimitBreach" type="checkbox" defaultChecked={values.blockOnLimitBreach} /> Block beyond credit limit</label><label className="check-row"><input name="blockOnOverdue" type="checkbox" defaultChecked={values.blockOnOverdue} /> Block when invoices are overdue</label><label className="check-row"><input name="autoRoundOff" type="checkbox" defaultChecked={values.autoRoundOff} /> Round invoice total to nearest rupee</label><label className="field"><span>Default print layout</span><select name="defaultPrintLayout" defaultValue={values.defaultPrintLayout}><option value="THERMAL_80MM">80 mm thermal</option><option value="A5">A5</option><option value="A4">A4</option></select></label></section><section className="panel settings-card"><p className="eyebrow">DIRECT SMS</p><h2>SMS adapter</h2><label className="field"><span>Provider</span><select name="smsProvider" defaultValue={values.smsProvider}><option value="CONSOLE">Console fallback</option><option value="GENERIC_JSON">Generic JSON API</option></select></label><label className="field"><span>Endpoint</span><input name="smsEndpoint" defaultValue={values.smsEndpoint} /></label><label className="field"><span>API key {values.smsApiKeySet && "(configured)"}</span><input name="smsApiKey" type="password" placeholder={values.smsApiKeySet ? "Leave blank to retain" : "Bearer API key"} /></label><label className="field"><span>Sender ID</span><input name="smsSender" defaultValue={values.smsSender} /></label></section><section className="panel settings-card"><p className="eyebrow">DIRECT EMAIL</p><h2>Email adapter</h2><label className="field"><span>Provider</span><select name="emailProvider" defaultValue={values.emailProvider}><option value="CONSOLE">Console fallback</option><option value="GENERIC_JSON">Generic JSON API</option></select></label><label className="field"><span>Endpoint</span><input name="emailEndpoint" defaultValue={values.emailEndpoint} /></label><label className="field"><span>API key {values.emailApiKeySet && "(configured)"}</span><input name="emailApiKey" type="password" placeholder={values.emailApiKeySet ? "Leave blank to retain" : "Bearer API key"} /></label><label className="field"><span>From address</span><input name="emailFrom" defaultValue={values.emailFrom} /></label></section><div className="settings-save"><button className="button" type="submit">Save outlet settings</button></div></form></div>;
}
