"use client";
import { EmptyRow } from "@/components/shell/empty-row";

import { Download, FileSpreadsheet, MessageCircle, Printer, Search, XCircle } from "lucide-react";
import { useMemo, useState, useTransition } from "react";
import { approveBillCancellation, requestBillCancellation } from "@/server/billing/actions";
import type { listBills } from "@/server/billing/queries";
import { BillingNav } from "@/components/billing/nav";

type Row = Awaited<ReturnType<typeof listBills>>[number];
export function BillRegister({ rows }: { rows: Row[] }) {
  const [query, setQuery] = useState(""); const [type, setType] = useState(""); const [status, setStatus] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [layout, setLayout] = useState("A5"); const [message, setMessage] = useState<string>(); const [working, start] = useTransition();
  const filtered = useMemo(() => rows.filter((row) => (!query || `${row.docNumber} ${row.customer} ${row.vehicleNo ?? ""}`.toLowerCase().includes(query.toLowerCase())) && (!type || row.type === type) && (!status || row.status === status)), [query, rows, status, type]);
  const params = `ids=${selected.join(",")}&layout=${layout}`;
  function cancel(row: Row) { const reason = prompt(`Reason for cancelling ${row.docNumber}`); if (!reason) return; start(async () => { const result = await requestBillCancellation({ billId: row.id, reason }); setMessage(result.ok ? "Cancellation sent for manager approval." : result.error); }); }
  function approve(row: Row) { const reason = prompt(`Manager approval note for ${row.docNumber}`); if (!reason) return; start(async () => { const result = await approveBillCancellation({ billId: row.id, approve: true, reason }); setMessage(result.ok ? "Bill cancelled; its number has been retained." : result.error); }); }
  return <div className="page billing-page"><BillingNav /><div className="section-head"><div><p className="eyebrow">IMMUTABLE REGISTER</p><h1>Sales bills</h1><p className="muted page-lede">Search, filter, share, export and bulk-print posted invoices across the selected outlet scope.</p></div><a className="button button-secondary" href="/api/billing/export"><FileSpreadsheet size={15} /> Excel</a></div>{message && <div className="info-bar">{message}</div>}
    <div className="panel register-panel"><div className="register-tools"><label className="search"><Search size={14} /><input placeholder="Bill, customer, vehicle…" value={query} onChange={(event) => setQuery(event.target.value)} /></label><select className="filter" value={type} onChange={(event) => setType(event.target.value)}><option value="">All bill types</option>{["CASH", "CREDIT", "COUNTER", "CONSOLIDATED", "CREDIT_NOTE"].map((value) => <option key={value}>{value}</option>)}</select><select className="filter" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option>POSTED</option><option>CANCELLED</option></select><select className="filter" value={layout} onChange={(event) => setLayout(event.target.value)}><option value="THERMAL_80MM">80 mm thermal</option><option value="A5">A5</option><option value="A4">A4</option></select><button className="button button-secondary" disabled={!selected.length} onClick={() => window.open(`/billing/print?${params}`, "_blank")}><Printer size={15} /> Print {selected.length || ""}</button><a aria-disabled={!selected.length} className="button button-secondary" href={selected.length ? `/api/billing/pdf?${params}` : undefined}><Download size={15} /> PDF</a></div>
      <div className="table-wrap"><table><thead><tr><th><input type="checkbox" checked={Boolean(filtered.length) && filtered.every((row) => selected.includes(row.id))} onChange={(event) => setSelected(event.target.checked ? filtered.map((row) => row.id) : [])} /></th><th>Bill</th><th>Date / time</th><th>Type</th><th>Customer / vehicle</th><th>Payment</th><th className="num">Total</th><th>Status</th><th>Output</th><th /></tr></thead><tbody>{filtered.map((row) => <tr key={row.id}><td><input type="checkbox" checked={selected.includes(row.id)} onChange={(event) => setSelected(event.target.checked ? [...selected, row.id] : selected.filter((id) => id !== row.id))} /></td><td className="sticky-col"><strong>{row.docNumber}</strong><small className="table-sub">{row.outlet}</small></td><td>{row.date}<small className="table-sub">{row.time} · {row.channel}</small></td><td><span className="badge">{row.type.replace("_", " ")}</span></td><td>{row.customer}<small className="table-sub">{row.vehicleNo || "No vehicle"}</small></td><td>{row.payment}</td><td className="num strong">{row.totalDisplay}</td><td><span className={`badge ${row.status === "CANCELLED" ? "alert" : row.cancellationPending ? "warn" : "ok"}`}>{row.status === "CANCELLED" ? "Cancelled" : row.cancellationPending ? "Approval due" : "Posted"}</span></td><td>{row.printed ? `${row.printCount} print${row.printCount === 1 ? "" : "s"}` : "Not printed"}<small className="table-sub">{row.irn ? "IRN stored" : "No IRN"}</small></td><td><div className="row-actions"><a title="WhatsApp" href={`https://wa.me/${row.mobile?.replace(/\D/g, "") ?? ""}?text=${encodeURIComponent(`Invoice ${row.docNumber} for ${row.totalDisplay}`)}`} target="_blank"><MessageCircle size={14} /></a>{row.status === "POSTED" && !row.cancellationPending && <button disabled={working} onClick={() => cancel(row)} title="Request cancellation"><XCircle size={14} /></button>}{row.cancellationPending && <button disabled={working} onClick={() => approve(row)}>Approve</button>}</div></td></tr>)}{filtered.length === 0 && <EmptyRow colSpan={10} message="No bills match these filters." hint="Try widening the date range or clearing a filter." />}</tbody><tfoot><tr className="totals-row"><td colSpan={6}>{filtered.length} bills</td><td className="num">—</td><td colSpan={3}>{selected.length} selected</td></tr></tfoot></table></div>
    </div></div>;
}
