"use client";

import { useState } from "react";
import { generateConsolidatedBill } from "@/server/billing/actions";
import type { getBillingOptions, listConsolidationCandidates } from "@/server/billing/queries";
import { BillingNav } from "@/components/billing/nav";

type Options = Awaited<ReturnType<typeof getBillingOptions>>; type Candidate = Awaited<ReturnType<typeof listConsolidationCandidates>>[number];
export function ConsolidatedScreen({ options, candidates, today }: { options: Options; candidates: Candidate[]; today: string }) {
  const [message, setMessage] = useState<string>(); const [savedId, setSavedId] = useState<string>();
  async function submit(data: FormData) { const result = await generateConsolidatedBill(Object.fromEntries(data)); if (result.ok) { setSavedId(result.id); setMessage(`Generated ${result.docNumber}`); } else setMessage(result.error); }
  return <div className="page billing-page"><BillingNav /><div className="section-head"><div><p className="eyebrow">PERIODICAL INVOICE</p><h1>Consolidated billing</h1><p className="muted page-lede">Roll unbilled signed credit slips into one customer invoice with the chosen presentation.</p></div></div>{message && <div className="info-bar">{message} {savedId && <a href={`/api/billing/pdf?ids=${savedId}&layout=A4`}>Download invoice</a>}</div>}
    {options.editable && <form action={submit} className="panel consolidation-form"><label className="field"><span>Customer</span><select name="customerId" required><option value="">Select customer</option>{options.customers.map((customer) => <option value={customer.id} key={customer.id}>{customer.code} · {customer.name}</option>)}</select></label><label className="field"><span>From</span><input name="fromDate" type="date" required defaultValue={new Date(Date.now() - 30 * 86_400_000).toISOString().slice(0, 10)} /></label><label className="field"><span>To</span><input name="toDate" type="date" required defaultValue={today} /></label><label className="field"><span>Itemisation</span><select name="format"><option value="DATE_WISE">Date-wise summary</option><option value="VEHICLE_WISE">Vehicle-wise summary</option><option value="SLIP_WISE">Slip-wise itemised</option><option value="PRODUCT_WISE">Product-wise summary</option></select></label><label className="field"><span>Document</span><select name="invoiceKind"><option value="BILL_OF_SUPPLY">Bill of supply</option><option value="GST_INVOICE">GST invoice</option></select></label><label className="field"><span>Remarks</span><input name="remarks" /></label><button className="button" type="submit">Generate consolidated bill</button></form>}
    <div className="panel register-panel"><div className="register-tools"><strong>Unbilled customer slips</strong><span className="muted">The generated bill preserves each source slip link.</span></div><div className="table-wrap"><table><thead><tr><th>Customer</th><th>Period</th><th className="num">Slips</th><th className="num">Value</th></tr></thead><tbody>{candidates.map((candidate) => <tr key={candidate.customerId}><td>{candidate.code} · {candidate.customer}</td><td>{candidate.from} — {candidate.to}</td><td className="num">{candidate.count}</td><td className="num strong">{candidate.amountDisplay}</td></tr>)}</tbody><tfoot><tr className="totals-row"><td colSpan={4}>{candidates.length ? `${candidates.length} customers ready to consolidate` : "No unbilled slips in the selected outlet"}</td></tr></tfoot></table></div></div>
  </div>;
}
