"use client";
import { EmptyRow } from "@/components/shell/empty-row";

import { useMemo, useState, useTransition } from "react";
import { issueShortCredit, resolveShortCredit } from "@/server/billing/actions";
import type { getBillingOptions, listShortCredits } from "@/server/billing/queries";
import { BillingNav } from "@/components/billing/nav";

type Options = Awaited<ReturnType<typeof getBillingOptions>>; type Row = Awaited<ReturnType<typeof listShortCredits>>[number];
export function RunningShortScreen({ options, rows, today, time }: { options: Options; rows: Row[]; today: string; time: string }) {
  const [status, setStatus] = useState("ISSUED"); const [recoverMode, setRecoverMode] = useState(options.editable ? options.paymentModes[0]?.id ?? "" : ""); const [message, setMessage] = useState<string>(); const [working, start] = useTransition();
  const visible = useMemo(() => rows.filter((row) => !status || row.status === status), [rows, status]);
  function resolve(row: Row, resolution: "CONVERT" | "RECOVER" | "WRITE_OFF") { const reason = prompt(`${resolution.replace("_", " ")} reason for ${row.docNumber}`); if (!reason) return; start(async () => { const result = await resolveShortCredit({ id: row.id, resolution, reason, paymentModeId: resolution === "RECOVER" ? recoverMode : "" }); setMessage(result.ok ? `${row.docNumber} resolved.` : result.error); }); }
  async function submit(formData: FormData) { const result = await issueShortCredit(Object.fromEntries(formData)); setMessage(result.ok ? `Issued ${result.docNumber}` : result.error); }
  return <div className="page billing-page"><BillingNav /><div className="section-head"><div><p className="eyebrow">NOZZLE SLIP</p><h1>Running short credit</h1><p className="muted page-lede">Temporary signed credit, kept visible until converted, recovered or approved for write-off.</p></div></div>{message && <div className="info-bar">{message}</div>}
    {options.editable && <form action={submit} className="panel short-form"><label className="field"><span>Date</span><input name="businessDate" type="date" defaultValue={today} /></label><label className="field"><span>Time</span><input name="issuedTime" type="time" defaultValue={time} /></label><label className="field"><span>Shift</span><select name="shiftEntryId" required><option value="">Select</option>{options.shiftEntries.map((shift) => <option value={shift.id} key={shift.id}>{shift.label}</option>)}</select></label><label className="field"><span>Customer</span><select name="customerId"><option value="">Unregistered</option>{options.customers.map((customer) => <option value={customer.id} key={customer.id}>{customer.name}</option>)}</select></label><label className="field"><span>Name on slip</span><input name="customerName" required /></label><label className="field"><span>Mobile</span><input name="mobile" /></label><label className="field"><span>Vehicle</span><input name="vehicleNo" /></label><label className="field"><span>Driver</span><input name="driverName" /></label><label className="field"><span>Salesman</span><select name="salesmanEmployeeId" required><option value="">Select</option>{options.employees.map((employee) => <option value={employee.id} key={employee.id}>{employee.name}</option>)}</select></label><label className="field"><span>Nozzle</span><select name="nozzleId" required><option value="">Select</option>{options.nozzles.map((nozzle) => <option value={nozzle.id} key={nozzle.id}>{nozzle.label}</option>)}</select></label><label className="field"><span>Product</span><select name="productId" required><option value="">Select</option>{options.products.filter((product) => product.isFuel).map((product) => <option value={product.id} key={product.id}>{product.name} · ₹{product.rate}</option>)}</select></label><label className="field"><span>Quantity (L)</span><input name="quantity" inputMode="decimal" required /></label><label className="field wide"><span>Remarks</span><input name="remarks" /></label><button className="button" type="submit">Issue slip</button></form>}
    <div className="panel register-panel"><div className="register-tools"><select className="filter" value={status} onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option>ISSUED</option><option>CONVERTED</option><option>RECOVERED</option><option>WRITTEN_OFF</option></select>{options.editable && <label className="field compact-field"><span>Recovery mode</span><select value={recoverMode} onChange={(event) => setRecoverMode(event.target.value)}>{options.paymentModes.filter((mode) => mode.type !== "CREDIT").map((mode) => <option value={mode.id} key={mode.id}>{mode.name}</option>)}</select></label>}<span className="muted">Open slips are ordered oldest first.</span></div><div className="table-wrap"><table><thead><tr><th>Slip</th><th>Date</th><th>Party / vehicle</th><th>Product</th><th>Salesman</th><th className="num">Litres</th><th className="num">Amount</th><th className="num">Age</th><th>Status</th><th /></tr></thead><tbody>{visible.map((row) => <tr key={row.id}><td>{row.docNumber}<small className="table-sub">{row.outlet}</small></td><td>{row.date}</td><td>{row.customer}<small className="table-sub">{row.vehicleNo || "—"}</small></td><td>{row.product}</td><td>{row.salesman}</td><td className="num">{row.quantityDisplay}</td><td className="num strong">{row.amountDisplay}</td><td className={`num ${row.status === "ISSUED" && row.ageDays > 30 ? "loss" : ""}`}>{row.ageDays} days</td><td><span className={`badge ${row.status === "ISSUED" && row.ageDays > 30 ? "alert" : row.status === "ISSUED" ? "warn" : "ok"}`}>{row.status}</span></td><td>{row.status === "ISSUED" && <div className="row-actions"><button disabled={working} onClick={() => resolve(row, "CONVERT")}>Convert</button><button disabled={working || !recoverMode} onClick={() => resolve(row, "RECOVER")}>Recover</button><button className="loss" disabled={working} onClick={() => resolve(row, "WRITE_OFF")}>Write off</button></div>}</td></tr>)}{visible.length === 0 && <EmptyRow colSpan={10} message="No running-short slips in this status." hint="They appear here as soon as a credit slip is issued at the pump." />}</tbody><tfoot><tr className="totals-row"><td colSpan={10}>{visible.length} slips · {visible.filter((row) => row.status === "ISSUED" && row.ageDays > 30).length} aged over 30 days</td></tr></tfoot></table></div></div>
  </div>;
}
