import type { Field } from "@/components/master/master-screen";
import type { MasterOptions } from "@/server/master/queries";

const productTypes = ["FUEL_MS", "FUEL_HSD", "FUEL_PREMIUM_MS", "FUEL_PREMIUM_HSD", "CNG", "LUBRICANT", "ADBLUE", "OTHER"];
const options = (values: string[]) => values.map((value) => ({ value, label: value.replaceAll("_", " ") }));
const assetStatus = options(["ACTIVE", "INACTIVE", "UNDER_MAINTENANCE", "DECOMMISSIONED"]);

export const fieldsFor = (entity: string, master: MasterOptions): Field[] => {
  switch (entity) {
    case "outlet": return [{ key: "code", label: "Outlet code", required: true }, { key: "name", label: "Outlet / stock point name", required: true }, { key: "legalName", label: "Legal name" }, { key: "omc", label: "OMC" }, { key: "dealerCode", label: "Dealer code" }, { key: "addressLine1", label: "Address" }, { key: "city", label: "City" }, { key: "state", label: "State" }, { key: "pincode", label: "Pincode" }, { key: "phone", label: "Phone" }, { key: "email", label: "Email" }, { key: "gstin", label: "GSTIN" }];
    case "product": return [{ key: "code", label: "Code", required: true }, { key: "name", label: "Product name", required: true }, { key: "productType", label: "Product type", kind: "select", required: true, options: options(productTypes) }, { key: "type", label: "Unit", kind: "select", required: true, options: options(["LITRE", "PIECE"]) }, { key: "hsnCode", label: "HSN / SAC" }, { key: "gstPct", label: "GST rate %", kind: "number" }, { key: "isFuel", label: "Fuel product", kind: "checkbox" }, { key: "isDensityTracked", label: "Track density", kind: "checkbox" }, { key: "currentPurchaseRate", label: "Current purchase rate", kind: "number" }, { key: "currentSellingRate", label: "Current selling rate", kind: "number" }, { key: "reorderLevel", label: "Reorder level", kind: "number" }];
    case "price": return [{ key: "productId", label: "Product", kind: "select", required: true, options: master.products, readOnlyOnEdit: true }, { key: "rate", label: "Selling rate", kind: "number", required: true }, { key: "purchaseRate", label: "Purchase rate", kind: "number" }, { key: "effectiveFrom", label: "Effective India time", kind: "datetime-local", required: true }, { key: "reason", label: "Reason" }];
    case "tank": return [{ key: "code", label: "Tank number", required: true }, { key: "name", label: "Name", required: true }, { key: "productId", label: "Product", kind: "select", required: true, options: master.products }, { key: "capacity", label: "Capacity (litres)", kind: "number", required: true }, { key: "deadStock", label: "Dead stock (litres)", kind: "number", required: true }, { key: "status", label: "Status", kind: "select", required: true, options: assetStatus }];
    case "dispensingUnit": return [{ key: "code", label: "DU number", required: true }, { key: "name", label: "Name", required: true }, { key: "make", label: "Make" }, { key: "model", label: "Model" }, { key: "serialNo", label: "Serial number" }, { key: "status", label: "Status", kind: "select", required: true, options: assetStatus }];
    case "nozzle": return [{ key: "code", label: "Nozzle number", required: true }, { key: "name", label: "Name", required: true }, { key: "dispensingUnitId", label: "Dispensing unit", kind: "select", required: true, options: master.dispensingUnits }, { key: "tankId", label: "Tank", kind: "select", required: true, options: master.tanks }, { key: "productId", label: "Product", kind: "select", required: true, options: master.products }, { key: "initialReading", label: "Commissioning reading", kind: "number", required: true }, { key: "currentReading", label: "Current cumulative reading", kind: "number", required: true }, { key: "meterDigits", label: "Meter digits", kind: "number", required: true }, { key: "status", label: "Status", kind: "select", required: true, options: assetStatus }];
    case "employee": return [{ key: "code", label: "Employee code", required: true }, { key: "name", label: "Name", required: true }, { key: "photoUrl", label: "Photo", kind: "file" }, { key: "phone", label: "Mobile" }, { key: "addressLine1", label: "Address" }, { key: "aadhaarLast4", label: "Aadhaar (last 4)" }, { key: "joinedOn", label: "Date of joining", kind: "date", required: true }, { key: "designation", label: "Designation" }, { key: "bankName", label: "Bank name" }, { key: "accountNumber", label: "Bank account" }, { key: "ifsc", label: "IFSC" }, { key: "status", label: "Status", kind: "select", required: true, options: options(["ACTIVE", "ON_LEAVE", "RESIGNED", "TERMINATED"]) }];
    case "shift": return [{ key: "code", label: "Code", required: true }, { key: "name", label: "Shift name", required: true }, { key: "startTime", label: "Start time", kind: "time", required: true }, { key: "endTime", label: "End time", kind: "time", required: true }, { key: "sequence", label: "Sequence", kind: "number", required: true }];
    case "customer": return [{ key: "code", label: "Customer code", required: true }, { key: "name", label: "Name", required: true }, { key: "gstin", label: "GSTIN" }, { key: "pan", label: "PAN" }, { key: "addressLine1", label: "Address" }, { key: "contactPerson", label: "Contact person" }, { key: "phone", label: "Mobile" }, { key: "creditLimit", label: "Credit limit", kind: "number", required: true }, { key: "creditDays", label: "Credit days", kind: "number", required: true }, { key: "openingBalance", label: "Opening balance", kind: "number", required: true }, { key: "openingBalanceType", label: "Opening Dr / Cr", kind: "select", required: true, options: options(["DEBIT", "CREDIT"]) }, { key: "discountPerLitre", label: "Discount / litre", kind: "number", required: true }, { key: "statementEmail", label: "Statement email" }, { key: "statementMobile", label: "Statement mobile" }, { key: "vehicles", label: "Vehicles (JSON)", kind: "vehicles" }];
    case "supplier": return [{ key: "code", label: "Supplier code", required: true }, { key: "name", label: "Name", required: true }, { key: "type", label: "Supplier type", kind: "select", required: true, options: options(["OMC", "LUBE", "OTHER"]) }, { key: "contactPerson", label: "Contact person" }, { key: "phone", label: "Phone" }, { key: "addressLine1", label: "Address" }, { key: "gstin", label: "GSTIN" }, { key: "pan", label: "PAN" }, { key: "creditDays", label: "Credit days", kind: "number", required: true }];
    case "paymentMode": return [{ key: "code", label: "Code", required: true }, { key: "name", label: "Mode name", required: true }, { key: "type", label: "Type", kind: "select", required: true, options: options(["CASH", "CREDIT", "CARD", "UPI", "WALLET", "FLEET_CARD", "OTHER"]) }, { key: "accountId", label: "Settlement ledger", kind: "select", options: master.accounts }, { key: "mdrPct", label: "MDR %", kind: "number" }, { key: "settlementDays", label: "Settlement days", kind: "number", required: true }, { key: "requiresReference", label: "Require reference", kind: "checkbox" }];
    case "expenseHead": return [{ key: "code", label: "Code", required: true }, { key: "name", label: "Expense head", required: true }, { key: "accountId", label: "Ledger", kind: "select", options: master.accounts }, { key: "description", label: "Description", kind: "textarea" }];
    case "accountGroup": return [{ key: "code", label: "Group code", required: true }, { key: "name", label: "Group name", required: true }, { key: "nature", label: "Nature", kind: "select", required: true, options: options(["ASSET", "LIABILITY", "INCOME", "EXPENSE", "EQUITY"]) }, { key: "parentId", label: "Parent group", kind: "select", options: master.accountGroups }, { key: "isBalanceSheet", label: "Balance sheet group", kind: "checkbox" }, { key: "sortOrder", label: "Sort order", kind: "number", required: true }];
    case "account": return [{ key: "code", label: "Ledger code", required: true }, { key: "name", label: "Ledger name", required: true }, { key: "groupId", label: "Account group", kind: "select", required: true, options: master.accountGroups }, { key: "nature", label: "Nature", kind: "select", required: true, options: options(["ASSET", "LIABILITY", "INCOME", "EXPENSE", "EQUITY"]) }, { key: "normalBalance", label: "Normal balance", kind: "select", required: true, options: options(["DEBIT", "CREDIT"]) }, { key: "openingBalance", label: "Opening balance", kind: "number", required: true }, { key: "openingBalanceType", label: "Opening Dr / Cr", kind: "select", required: true, options: options(["DEBIT", "CREDIT"]) }, { key: "isBankAccount", label: "Bank account", kind: "checkbox" }, { key: "bankName", label: "Bank name" }, { key: "accountNumber", label: "Account number" }, { key: "ifsc", label: "IFSC" }];
    case "calibration": return [{ key: "tankId", label: "Tank", kind: "select", required: true, options: master.tanks }, { key: "chartType", label: "Chart", kind: "select", required: true, options: options(["FUEL", "WATER"]) }, { key: "dipMm", label: "Dip (mm)", kind: "number", required: true }, { key: "litres", label: "Volume (litres)", kind: "number", required: true }];
    case "firm": return [{ key: "name", label: "Firm name", required: true }, { key: "legalName", label: "Legal name" }, { key: "addressLine1", label: "Address line 1" }, { key: "addressLine2", label: "Address line 2" }, { key: "city", label: "City" }, { key: "state", label: "State" }, { key: "stateCode", label: "State code" }, { key: "pincode", label: "Pincode" }, { key: "gstin", label: "GSTIN" }, { key: "pan", label: "PAN" }, { key: "logoUrl", label: "Logo", kind: "file" }, { key: "bankName", label: "Bank name" }, { key: "bankAccountName", label: "Account name" }, { key: "bankAccountNumber", label: "Account number" }, { key: "bankIfsc", label: "IFSC" }, { key: "invoiceTerms", label: "Invoice terms", kind: "textarea" }, { key: "declarationText", label: "Declaration", kind: "textarea" }, { key: "signatureUrl", label: "Signature image", kind: "file" }, { key: "documentSeries", label: "Invoice series (JSON)", kind: "vehicles" }];
    default: return [];
  }
};
