import { Document, Image, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import React from "react";
import { formatNumber } from "@/lib/format";
import type { getPrintableBills } from "@/server/billing/queries";

type Bills = Awaited<ReturnType<typeof getPrintableBills>>;
type Layout = "THERMAL_80MM" | "A5" | "A4";
const styles = StyleSheet.create({ page: { color: "#16212d", fontFamily: "Helvetica", fontSize: 9, padding: 24 }, thermal: { fontSize: 7, padding: 10 }, header: { borderBottom: "1 solid #26384b", marginBottom: 10, paddingBottom: 8 }, firm: { fontSize: 16, fontWeight: 700 }, thermalFirm: { fontSize: 11 }, muted: { color: "#5e6c7b", fontSize: 7 }, titleRow: { display: "flex", flexDirection: "row", justifyContent: "space-between", marginBottom: 10 }, title: { fontSize: 12, fontWeight: 700 }, metaGrid: { border: "1 solid #cad2dc", display: "flex", flexDirection: "row", flexWrap: "wrap", marginBottom: 10, padding: 6 }, meta: { width: "50%", marginBottom: 3 }, full: { width: "100%" }, table: { border: "1 solid #aeb9c6", marginBottom: 10 }, row: { borderBottom: "1 solid #d7dde5", display: "flex", flexDirection: "row", minHeight: 22 }, head: { backgroundColor: "#e8eef3", fontWeight: 700 }, c1: { padding: 5, width: "7%" }, c2: { padding: 5, width: "35%" }, c3: { padding: 5, textAlign: "right", width: "14%" }, c4: { padding: 5, textAlign: "right", width: "14%" }, c5: { padding: 5, textAlign: "right", width: "15%" }, c6: { padding: 5, textAlign: "right", width: "15%" }, totals: { alignSelf: "flex-end", width: "48%" }, totalRow: { display: "flex", flexDirection: "row", justifyContent: "space-between", paddingVertical: 2 }, grand: { borderTop: "1 solid #172532", fontSize: 12, fontWeight: 700, marginTop: 3, paddingTop: 5 }, words: { borderTop: "1 solid #cad2dc", fontSize: 8, marginTop: 10, paddingTop: 7 }, footer: { borderTop: "1 solid #cad2dc", color: "#5e6c7b", fontSize: 7, marginTop: 14, paddingTop: 7 }, qr: { height: 62, marginTop: 8, width: 62 }, cancelled: { color: "#b4232b", fontSize: 22, fontWeight: 700, marginVertical: 8, textAlign: "center" } });

export function InvoicePdf({ bills, layout, qrCodes }: { bills: Bills; layout: Layout; qrCodes: Record<string, string> }) {
  return <Document>{bills.map((bill) => <Page key={bill.id} size={layout === "THERMAL_80MM" ? [226.77, 500 + bill.lines.length * 24] : layout} style={[styles.page, ...(layout === "THERMAL_80MM" ? [styles.thermal] : [])]}>
    <View style={styles.header}><Text style={[styles.firm, ...(layout === "THERMAL_80MM" ? [styles.thermalFirm] : [])]}>{bill.outlet.firm?.legalName ?? bill.outlet.name}</Text><Text style={styles.muted}>{[bill.outlet.addressLine1, bill.outlet.city, bill.outlet.state, bill.outlet.pincode].filter(Boolean).join(", ")}</Text><Text style={styles.muted}>GSTIN: {bill.outlet.gstin ?? bill.outlet.firm?.gstin ?? "—"}</Text></View>
    <View style={styles.titleRow}><Text style={styles.title}>{bill.invoiceKind === "GST_INVOICE" ? "TAX INVOICE" : "BILL OF SUPPLY"}</Text><Text>{bill.docNumber}</Text></View>
    {bill.status === "CANCELLED" && <Text style={styles.cancelled}>CANCELLED</Text>}
    <View style={styles.metaGrid}><Text style={styles.meta}>Date: {bill.businessDate.toISOString().slice(0, 10)}</Text><Text style={styles.meta}>Time: {new Intl.DateTimeFormat("en-IN", { timeZone: "Asia/Kolkata", hour: "2-digit", minute: "2-digit" }).format(bill.billedAt)}</Text><Text style={styles.meta}>Customer: {bill.customer?.name ?? bill.customerName ?? "Walk-in"}</Text><Text style={styles.meta}>GSTIN: {bill.customer?.gstin ?? "—"}</Text><Text style={styles.meta}>Vehicle: {bill.vehicleNo ?? bill.vehicle?.vehicleNo ?? "—"}</Text><Text style={styles.meta}>Driver: {bill.driverName ?? bill.vehicle?.driverName ?? "—"}</Text><Text style={styles.meta}>Salesman: {bill.salesman?.name ?? "—"}</Text><Text style={styles.meta}>Nozzle: {bill.nozzle?.code ?? "—"}</Text></View>
    <View style={styles.table}><View style={[styles.row, styles.head]}><Text style={styles.c1}>#</Text><Text style={styles.c2}>Item / HSN</Text><Text style={styles.c3}>Qty</Text><Text style={styles.c4}>Rate</Text><Text style={styles.c5}>GST</Text><Text style={styles.c6}>Amount</Text></View>{bill.lines.map((line) => <View key={line.id} style={styles.row}><Text style={styles.c1}>{line.lineNo}</Text><Text style={styles.c2}>{line.description ?? line.product.name}{"\n"}{line.hsnCode ?? line.product.hsnCode ?? ""}</Text><Text style={styles.c3}>{formatNumber(line.quantity)}</Text><Text style={styles.c4}>{formatNumber(line.rate)}</Text><Text style={styles.c5}>{formatNumber(line.gstAmount)}</Text><Text style={styles.c6}>{formatNumber(line.amount)}</Text></View>)}</View>
    <View style={styles.totals}><View style={styles.totalRow}><Text>Taxable</Text><Text>INR {formatNumber(bill.taxableValue)}</Text></View><View style={styles.totalRow}><Text>CGST / SGST</Text><Text>{formatNumber(bill.cgstAmount)} / {formatNumber(bill.sgstAmount)}</Text></View><View style={styles.totalRow}><Text>IGST / cess</Text><Text>{formatNumber(bill.igstAmount)} / {formatNumber(bill.cessAmount)}</Text></View><View style={styles.totalRow}><Text>Round-off</Text><Text>{formatNumber(bill.roundOff)}</Text></View><View style={[styles.totalRow, styles.grand]}><Text>Grand total</Text><Text>INR {formatNumber(bill.totalAmount)}</Text></View></View>
    <Text style={styles.words}>{bill.amountInWords}</Text>{qrCodes[bill.id] && <Image src={qrCodes[bill.id]} style={styles.qr} />}{bill.irn && <Text style={styles.muted}>IRN: {bill.irn}{"\n"}Ack: {bill.acknowledgementNo ?? "—"}</Text>}
    <Text style={styles.footer}>{bill.outlet.firm?.invoiceTerms ?? "Thank you."}{"\n"}{bill.outlet.firm?.declarationText ?? ""}{"\n"}Computer-generated document · {bill.settlements.map((entry) => entry.paymentMode.name).join(" + ") || "Credit"}</Text>
  </Page>)}</Document>;
}
